# Generated by Django 5.0.6 on 2026-07-21 02:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField()),
                ('tipo_objetivo', models.CharField(choices=[('HABITACION', 'Habitacion'), ('RESERVACION', 'Reservacion'), ('SERVICIO', 'Servicio')], max_length=20)),
                ('objetivo_id', models.UUIDField()),
                ('calificacion', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('aprobada', 'Aprobada'), ('oculta', 'Oculta')], default='aprobada', max_length=20)),
            ],
            options={
                'db_table': 'resenas',
                'indexes': [models.Index(fields=['tipo_objetivo', 'objetivo_id'], name='resenas_tipo_ob_b46313_idx')],
            },
        ),
        migrations.CreateModel(
            name='RespuestaResena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('autor_tipo', models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente')], max_length=20)),
                ('autor_id', models.UUIDField()),
                ('contenido', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='reviews.resena')),
            ],
            options={
                'db_table': 'respuestas_resena',
                'ordering': ['creado_en'],
            },
        ),
    ]
