# Generated by Django 5.0.6 on 2026-07-09 04:20

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField()),
                ('tipo_objetivo', models.CharField(choices=[('HABITACION', 'Habitacion'), ('RESERVACION', 'Reservacion'), ('SERVICIO', 'Servicio')], max_length=20)),
                ('objetivo_id', models.UUIDField()),
                ('calificacion', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'resenas',
                'indexes': [models.Index(fields=['tipo_objetivo', 'objetivo_id'], name='resenas_tipo_ob_b46313_idx')],
            },
        ),
    ]
