# Generated by Django 5.0.6 on 2026-07-21 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=30, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('url_pdf', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservacion_id', models.UUIDField(blank=True, null=True)),
                ('carrito_id', models.UUIDField(blank=True, null=True)),
                ('cliente_id', models.UUIDField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('id_transaccion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reembolsos',
            },
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('carrito_id__isnull', True), ('reservacion_id__isnull', False)), models.Q(('carrito_id__isnull', False), ('reservacion_id__isnull', True)), _connector='OR'), name='pago_reservacion_xor_carrito'),
        ),
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='payments.pago'),
        ),
        migrations.AddField(
            model_name='reembolso',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='payments.pago'),
        ),
    ]
