# Generated by Django 5.0.6 on 2026-07-09 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin')], default='cliente', max_length=20)),
                ('estado_cuenta', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('idioma_preferido', models.CharField(blank=True, max_length=10)),
                ('puntos_lealtad', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='accounts.usuario')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
