# Generated by Django 5.0.6 on 2026-07-08 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='correo', max_length=254, unique=True)),
                ('password_hash', models.CharField(db_column='contrasena_hash', max_length=255)),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin')], db_column='rol', default='cliente', max_length=20)),
                ('account_status', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo')], db_column='estado_cuenta', default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
