# Generated by Django 5.0.6 on 2026-07-21 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carritos',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_id', models.UUIDField()),
                ('habitacion_id', models.UUIDField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(choices=[('draft', 'Draft'), ('pendiente_pago', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='draft', max_length=20)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'reservaciones',
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servicio_id', models.UUIDField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_uso', models.DateField(blank=True, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.carrito')),
            ],
            options={
                'db_table': 'carrito_items',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoReservacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='reservations.reservacion')),
            ],
            options={
                'db_table': 'historial_estados_reservacion',
                'ordering': ['-cambiado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReservacionServicio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servicio_id', models.UUIDField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='reservations.reservacion')),
            ],
            options={
                'db_table': 'reservacion_servicios',
            },
        ),
    ]
