# Generated by Django 5.0.6 on 2026-07-21 02:47

import django.db.models.deletion
import rooms.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('deshabilitada', 'Deshabilitada')], default='disponible', max_length=20)),
            ],
            options={
                'db_table': 'habitaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_maxima', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'tipos_habitacion',
            },
        ),
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=rooms.models.ruta_imagen_habitacion)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='rooms.habitacion')),
            ],
            options={
                'db_table': 'imagenes_habitacion',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='rooms.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='DisponibilidadHabitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=20)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='rooms.habitacion')),
            ],
            options={
                'db_table': 'disponibilidad_habitacion',
                'ordering': ['fecha'],
                'unique_together': {('habitacion', 'fecha')},
            },
        ),
    ]
